version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:80'
    environment:
      - APP_ENV=production
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
